"""Grid Agent task logic.

Grid is a standalone BSC Testnet agent. It can accept direct user tasks and
ERC-8183 jobs. AgentMarket is only one possible client of the agent and is not
part of the agent's runtime contract.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any


TESTNET_CAKE2 = "0x8d008B313C1d6C7fE2982F62d32Da7507cF43551"
TESTNET_WBNB = "0xae13d989daC2f0dEbFf460aC112a837C89BAa7cd"
TESTNET_PANCAKE_FEE = 2500
AGENT_ID = "grid-agent"
AGENT_VERSION = "1.0.0"


@dataclass(frozen=True)
class GridPlan:
    lower_price: float
    upper_price: float
    grid_levels: int
    interval_pct: float
    total_notional: float
    risk: str


def _parse_json_object(value: Any) -> dict[str, Any]:
    """Decode an optional JSON object from a task/job field."""
    if isinstance(value, dict):
        return value
    if not isinstance(value, str) or not value.strip():
        return {}
    try:
        parsed = json.loads(value)
    except json.JSONDecodeError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def task_parameters(task: dict[str, Any]) -> dict[str, Any]:
    """Extract parameters from direct tasks and ERC-8183 descriptions."""
    metadata = _parse_json_object(task.get("metadata"))
    description = _parse_json_object(task.get("description"))
    params = task.get("params")
    if isinstance(params, dict):
        merged_params = params
    else:
        description_params = description.get("params")
        merged_params = description_params if isinstance(description_params, dict) else {}
    return {**metadata, **description, **merged_params}


def build_grid_plan(task: dict[str, Any]) -> GridPlan:
    """Build a deterministic grid strategy from a direct task or ERC-8183 job."""
    parameters = task_parameters(task)

    lower = float(parameters.get("lower_price", 0))
    upper = float(parameters.get("upper_price", 0))
    levels = int(parameters.get("grid_levels", 0))
    notional = float(parameters.get("notional", 0))
    max_slippage_bps = int(parameters.get("max_slippage_bps", 150))

    if lower <= 0 or upper <= 0 or upper <= lower:
        raise ValueError("Grid range must have positive lower and upper prices with upper > lower")
    if levels < 2 or levels > 100:
        raise ValueError("grid_levels must be between 2 and 100")
    if notional <= 0:
        raise ValueError("notional must be positive")
    if max_slippage_bps < 0 or max_slippage_bps > 150:
        raise ValueError("max_slippage_bps exceeds the test guardrail")

    interval_pct = ((upper / lower) ** (1 / (levels - 1)) - 1) * 100
    risk = "conservative" if max_slippage_bps <= 50 else "standard"

    return GridPlan(
        lower_price=lower,
        upper_price=upper,
        grid_levels=levels,
        interval_pct=round(interval_pct, 6),
        total_notional=notional,
        risk=risk,
    )


def build_deliverable(task: dict[str, Any], *, source: str) -> dict[str, Any]:
    """Create a portable result manifest without marketplace-specific fields."""
    plan = build_grid_plan(task)
    task_id = str(task.get("task_id", task.get("jobId", task.get("id", ""))))
    return {
        "agent": {
            "id": AGENT_ID,
            "version": AGENT_VERSION,
        },
        "task": {
            "id": task_id,
            "source": source,
        },
        "status": "completed",
        "execution": "strategy_only",
        "execution_market": {
            "network": "bsc-testnet",
            "protocol": "pancake-v3",
            "token_in": {
                "symbol": "CAKE2",
                "address": TESTNET_CAKE2,
            },
            "token_out": {
                "symbol": "WBNB",
                "address": TESTNET_WBNB,
            },
            "fee": TESTNET_PANCAKE_FEE,
        },
        "plan": {
            "lower_price": plan.lower_price,
            "upper_price": plan.upper_price,
            "grid_levels": plan.grid_levels,
            "interval_pct": plan.interval_pct,
            "total_notional": plan.total_notional,
            "risk": plan.risk,
        },
        "note": "Strategy generated by the standalone Grid Agent. No user funds were traded by this strategy-only operation.",
    }


def fulfill_grid_job(job: dict[str, Any]) -> str:
    """Produce the deliverable for one funded ERC-8183 Grid job."""
    return json.dumps(build_deliverable(job, source="erc-8183"), separators=(",", ":"))


def fulfill_user_task(task: dict[str, Any]) -> dict[str, Any]:
    """Process one direct user task through the public agent interface."""
    return build_deliverable(task, source="direct-user")


if __name__ == "__main__":
    sample = {
        "task_id": "local-grid-1",
        "params": {
            "lower_price": 600.0,
            "upper_price": 700.0,
            "grid_levels": 12,
            "notional": 100.0,
            "max_slippage_bps": 50,
        },
    }
    print(json.dumps(fulfill_user_task(sample), indent=2))
