import { createHmac } from "node:crypto";
import { BNB_TESTNET, createClient, signerFromPrivateKey } from "@altananetwork/sdk";
import { createPublicClient, http, type Address, type Hex, encodeFunctionData } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { bscTestnet } from "viem/chains";

const PORT = Number(process.env.EXECUTION_PORT || 8788);
const AGENT = (process.env.EXECUTION_AGENT_KIND || "defi-agent").trim().toLowerCase();
const NETWORK = (process.env.NETWORK || "bsc-testnet").trim().toLowerCase();
const CHAIN_ID = 97;
const ERC20_ABI = [{ type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "remaining", type: "uint256" }] }] as const;
const PANCAKE_V3_ABI = [{ type: "function", name: "exactInputSingle", stateMutability: "payable", inputs: [{ name: "params", type: "tuple", components: [{ name: "tokenIn", type: "address" }, { name: "tokenOut", type: "address" }, { name: "fee", type: "uint24" }, { name: "recipient", type: "address" }, { name: "amountIn", type: "uint256" }, { name: "amountOutMinimum", type: "uint256" }, { name: "sqrtPriceLimitX96", type: "uint160" }] }], outputs: [{ name: "amountOut", type: "uint256" }] }] as const;
const SWAP_SELECTOR = "0x04e45aaf";
const publicClient = createPublicClient({ chain: bscTestnet, transport: http(process.env.BSC_TESTNET_RPC_URL || "https://bsc-testnet-rpc.publicnode.com") });

function isAddress(value: string): value is Address { return /^0x[a-fA-F0-9]{40}$/.test(value); }
function isHex(value: string): value is Hex { return /^0x[a-fA-F0-9]*$/.test(value); }
function normalizePrivateKey(value: string): `0x${string}` { const raw = value.startsWith("0x") ? value.slice(2) : value; if (!/^[0-9a-fA-F]{64}$/.test(raw)) throw new Error("ALTANA_SESSION_PRIVATE_KEY must be a 32-byte hex private key"); return `0x${raw}`; }
function addresses(name: string): Address[] { return (process.env[name] || "").split(",").map(v => v.trim()).filter(Boolean).map(v => { if (!isAddress(v)) throw new Error(`${name} contains an invalid address`); return v as Address; }); }
function selectors(name: string): Hex[] { return (process.env[name] || "").split(",").map(v => v.trim()).filter(Boolean).map(v => { if (!isHex(v) || v.length !== 10) throw new Error(`${name} contains an invalid selector`); return v as Hex; }); }
function deriveJobSessionPrivateKey(jobId: number): `0x${string}` { if (!Number.isSafeInteger(jobId) || jobId <= 0) throw new Error("jobId must be a positive integer"); const master = normalizePrivateKey(process.env.ALTANA_SESSION_PRIVATE_KEY || ""); return `0x${createHmac("sha256", master.slice(2)).update(`${AGENT}-job-session:${jobId}`).digest("hex")}`; }
function descriptor(jobId: number, walletAddress: string) { if (!isAddress(walletAddress)) throw new Error("walletAddress must be a valid EVM address"); const sessionPrivateKey = deriveJobSessionPrivateKey(jobId); const account = privateKeyToAccount(sessionPrivateKey); const sessionAddress = account.address; const sessionPublicKey = account.publicKey as Hex; const expiry = Number(process.env.ALTANA_SESSION_EXPIRY || 0); const spendToken = (process.env.ALTANA_SESSION_SPEND_TOKEN || "").trim(); const spendLimit = BigInt(process.env.ALTANA_SESSION_SPEND_LIMIT || "0"); const nativeSpendLimit = BigInt(process.env.ALTANA_SESSION_NATIVE_SPEND_LIMIT || "0"); const allowedCalls = addresses("ALTANA_ALLOWED_TARGETS"); const allowedSelectors = selectors("ALTANA_ALLOWED_SELECTORS"); if (!Number.isSafeInteger(expiry) || expiry <= Math.floor(Date.now() / 1000)) throw new Error("ALTANA_SESSION_EXPIRY is missing or expired"); if (!isAddress(spendToken)) throw new Error("ALTANA_SESSION_SPEND_TOKEN must be configured"); if (spendLimit <= 0n || nativeSpendLimit <= 0n) throw new Error("Altana session spend limits must be positive"); if (allowedCalls.length === 0 || allowedSelectors.length === 0) throw new Error("Altana target and selector allowlists are required"); return { walletAddress: walletAddress as Address, sessionAddress, sessionPublicKey, sessionPrivateKey, expiry, spendToken: spendToken as Address, spendLimit, nativeSpendLimit, allowedCalls, allowedSelectors }; }
function assertAllowed(to: Address, data: Hex, d: ReturnType<typeof descriptor>) { if (!d.allowedCalls.some(v => v.toLowerCase() === to.toLowerCase())) throw new Error(`Execution target ${to} is not allowlisted`); const selector = data.slice(0, 10).toLowerCase(); if (!d.allowedSelectors.some(v => selector === v.toLowerCase())) throw new Error(`Execution selector ${selector} is not allowlisted`); }
function buildSwapCall(body: Record<string, unknown>, d: ReturnType<typeof descriptor>) { const tokenIn = String(body.tokenIn || ""); const tokenOut = String(body.tokenOut || ""); const router = String(process.env.ALTANA_SWAP_ROUTER || ""); const fee = Number(body.fee ?? process.env.ALTANA_SWAP_FEE ?? 2500); const amountIn = BigInt(String(body.amountIn || "0")); const amountOutMinimum = BigInt(String(body.amountOutMinimum || "0")); const recipient = String(body.recipient || d.walletAddress); if (!isAddress(tokenIn) || !isAddress(tokenOut) || !isAddress(router) || !isAddress(recipient)) throw new Error("Swap addresses are invalid"); if (!Number.isInteger(fee) || fee < 0 || fee > 0xffffff) throw new Error("Swap fee is invalid"); if (amountIn <= 0n) throw new Error("amountIn must be positive"); if (recipient.toLowerCase() !== d.walletAddress.toLowerCase()) throw new Error("recipient must equal the authorized wallet"); if (amountIn > d.spendLimit) throw new Error("amountIn exceeds the Altana spend cap"); const swapData = encodeFunctionData({ abi: PANCAKE_V3_ABI, functionName: "exactInputSingle", args: [{ tokenIn: tokenIn as Address, tokenOut: tokenOut as Address, fee, recipient: recipient as Address, amountIn, amountOutMinimum, sqrtPriceLimitX96: 0n }] }); const call = { to: router as Address, data: swapData, value: 0n as bigint }; if (swapData.slice(0, 10).toLowerCase() !== SWAP_SELECTOR) throw new Error("Unexpected PancakeSwap exactInputSingle selector"); assertAllowed(call.to, call.data, d); return { call, tokenIn: tokenIn as Address, router: router as Address, amountIn }; }
async function assertAllowance(walletAddress: Address, tokenIn: Address, router: Address, amountIn: bigint) { const allowance = await publicClient.readContract({ address: tokenIn, abi: ERC20_ABI, functionName: "allowance", args: [walletAddress, router] }); if (allowance < amountIn) throw new Error(`ERC-20 allowance is ${allowance.toString()} but ${amountIn.toString()} is required for the PancakeSwap router; user approval is required before agent execution`); }
async function executeSwap(body: Record<string, unknown>) { if (NETWORK !== "bsc-testnet") throw new Error("Execution is restricted to BSC Testnet"); const jobId = Number(body.jobId); const walletAddress = String(body.walletAddress || ""); if (!Number.isSafeInteger(jobId) || jobId <= 0) throw new Error("jobId is required"); const d = descriptor(jobId, walletAddress); const { call, tokenIn, router, amountIn } = buildSwapCall(body, d); await assertAllowance(d.walletAddress, tokenIn, router, amountIn); const session = { walletAddress: d.walletAddress, signer: signerFromPrivateKey(d.sessionPrivateKey), publicKey: d.sessionPublicKey, permissions: { calls: [{ to: router as Address }], spend: [{ limit: d.spendLimit, period: "day" as const, token: d.spendToken }, { limit: d.nativeSpendLimit, period: "day" as const }] }, expiry: d.expiry }; const client = createClient({ chains: [BNB_TESTNET] }); const result = await client.execute({ session, calls: [call], chainId: CHAIN_ID }); if (result.status === "FAILED") throw new Error(`Altana execute failed for ${result.callsId}`); return { agent: AGENT, network: NETWORK, chain_id: CHAIN_ID, calls_id: result.callsId, transaction_hash: result.transactionHash ?? null, status: result.status, action: "swap" }; }
async function preflight(body: Record<string, unknown>) { const jobId = Number(body.jobId); const walletAddress = String(body.walletAddress || ""); if (!Number.isSafeInteger(jobId) || jobId <= 0) throw new Error("jobId is required"); const d = descriptor(jobId, walletAddress); const { call, tokenIn, router, amountIn } = buildSwapCall(body, d); const allowance = await publicClient.readContract({ address: tokenIn, abi: ERC20_ABI, functionName: "allowance", args: [d.walletAddress, router] }); return { broadcast: false, agent: AGENT, network: NETWORK, chain_id: CHAIN_ID, job_id: jobId, targets: [call.to], selectors: [call.data.slice(0, 10)], recipient: walletAddress, requires_approval: allowance < amountIn, allowance: allowance.toString(), amount_in: amountIn.toString(), call }; }
function capabilityDescriptor(jobId: number) { const d = descriptor(jobId, (process.env.ALTANA_CAPABILITY_WALLET || process.env.ALTANA_SESSION_WALLET || "0x0000000000000000000000000000000000000000")); const router = String(process.env.ALTANA_SWAP_ROUTER || ""); const tokenOut = String(process.env.ALTANA_DEFAULT_TOKEN_OUT || "").trim(); const fee = Number(process.env.ALTANA_SWAP_FEE || 2500); const tokenInSymbol = String(process.env.ALTANA_SESSION_SPEND_TOKEN_SYMBOL || "").trim(); const tokenOutSymbol = String(process.env.ALTANA_DEFAULT_TOKEN_OUT_SYMBOL || "").trim(); return { type: "agent-execution-capability-v1", agent: AGENT, execution: "altana-scoped-session", wallet_provider: "altana", authorization_model: "scoped_session", network: NETWORK, chain_id: CHAIN_ID, protocol: "pancake-v3-swap", preflight_path: "/preflight", session_key_address: d.sessionAddress, session_key_public_key: d.sessionPublicKey, allowed_targets: isAddress(router) ? [router] : [], allowed_selectors: [SWAP_SELECTOR], selectors_required: true, private_key_exposed: false, session_expiry: d.expiry, execution_market: { token_in: d.spendToken, token_out: isAddress(tokenOut) ? tokenOut : null, token_in_symbol: tokenInSymbol || null, token_out_symbol: tokenOutSymbol || null, fee: Number.isInteger(fee) ? fee : 2500 } }; }
function response(res: any, status: number, body: unknown) { const raw = JSON.stringify(body); res.writeHead(status, { "content-type": "application/json", "content-length": Buffer.byteLength(raw) }); res.end(raw); }
const server = await import("node:http").then(({ createServer }) => createServer(async (req, res) => { try { const url = new URL(req.url || "/", "http://" + (req.headers.host || "127.0.0.1:" + PORT)); if (req.method === "GET" && url.pathname === "/health") return response(res, 200, { status: "ok", agent: AGENT, network: NETWORK, chain_id: CHAIN_ID }); if (req.method === "GET" && (url.pathname === "/execution-capabilities" || url.pathname === "/erc8183/execution-capabilities")) { const requestedJobId = Number(url.searchParams.get("job_id") || url.searchParams.get("jobId") || 0); if (!Number.isSafeInteger(requestedJobId) || requestedJobId <= 0) return response(res, 400, { error: "job_id is required" }); return response(res, 200, capabilityDescriptor(requestedJobId)); } if (req.method === "POST" && (url.pathname === "/preflight" || url.pathname === "/preflight/pancake" || url.pathname === "/execute-swap" || url.pathname === "/execute")) { const chunks: Buffer[] = []; for await (const chunk of req) chunks.push(Buffer.from(chunk)); const body = JSON.parse(Buffer.concat(chunks).toString("utf8")); if (!body || typeof body !== "object") throw new Error("Request body must be an object"); if (url.pathname === "/preflight" || url.pathname === "/preflight/pancake") return response(res, 200, await preflight(body)); return response(res, 200, await executeSwap(body)); } return response(res, 404, { error: "not_found" }); } catch (error) { return response(res, 400, { error: error instanceof Error ? error.message : String(error) }); } }));
server.listen(PORT, "127.0.0.1", () => console.log(`${AGENT} Altana execution listening on 127.0.0.1:${PORT}`));