import { createHmac } from "node:crypto";
import { createServer } from "node:http";
import { BNB_TESTNET, createClient, signerFromPrivateKey } from "@altananetwork/sdk";
import { createPublicClient, encodeFunctionData, http, type Address, type Hex } from "viem";
import { bscTestnet } from "viem/chains";

const PORT = Number(process.env.EXECUTION_PORT || 8788);
const NETWORK = "bsc-testnet" as const;
const CHAIN_ID = 97;
const SWAP_SELECTOR = "0x04e45aaf";
const publicClient = createPublicClient({ chain: bscTestnet, transport: http(process.env.BSC_TESTNET_RPC_URL || "https://bsc-testnet-rpc.publicnode.com") });

const SWAP_ABI = [{type:"function",name:"exactInputSingle",stateMutability:"payable",inputs:[{name:"params",type:"tuple",components:[{name:"tokenIn",type:"address"},{name:"tokenOut",type:"address"},{name:"fee",type:"uint24"},{name:"recipient",type:"address"},{name:"amountIn",type:"uint256"},{name:"amountOutMinimum",type:"uint256"},{name:"sqrtPriceLimitX96",type:"uint160"}]}],outputs:[{name:"amountOut",type:"uint256"}]}] as const;
const LP_ABI = [
 {type:"function",name:"decreaseLiquidity",stateMutability:"nonpayable",inputs:[{name:"params",type:"tuple",components:[{name:"tokenId",type:"uint256"},{name:"liquidity",type:"uint128"},{name:"amount0Min",type:"uint256"},{name:"amount1Min",type:"uint256"},{name:"deadline",type:"uint256"}]}],outputs:[{name:"amount0",type:"uint256"},{name:"amount1",type:"uint256"}]},
 {type:"function",name:"collect",stateMutability:"payable",inputs:[{name:"params",type:"tuple",components:[{name:"tokenId",type:"uint256"},{name:"recipient",type:"address"},{name:"amount0Max",type:"uint128"},{name:"amount1Max",type:"uint128"}]}],outputs:[{name:"amount0",type:"uint256"},{name:"amount1",type:"uint256"}]},
 {type:"function",name:"burn",stateMutability:"nonpayable",inputs:[{name:"tokenId",type:"uint256"}],outputs:[]},
 {type:"function",name:"mint",stateMutability:"payable",inputs:[{name:"params",type:"tuple",components:[{name:"token0",type:"address"},{name:"token1",type:"address"},{name:"fee",type:"uint24"},{name:"tickLower",type:"int24"},{name:"tickUpper",type:"int24"},{name:"amount0Desired",type:"uint256"},{name:"amount1Desired",type:"uint256"},{name:"amount0Min",type:"uint256"},{name:"amount1Min",type:"uint256"},{name:"recipient",type:"address"},{name:"deadline",type:"uint256"}]}],outputs:[{name:"tokenId",type:"uint256"},{name:"liquidity",type:"uint128"},{name:"amount0",type:"uint256"},{name:"amount1",type:"uint256"}]}
] as const;
const ERC20_ABI = [{type:"function",name:"allowance",stateMutability:"view",inputs:[{name:"owner",type:"address"},{name:"spender",type:"address"}],outputs:[{name:"remaining",type:"uint256"}]}] as const;

function isAddress(value:string): value is Address { return /^0x[a-f-f0-9]{40}$/i.test(value); }
function isHex(value:string): value is Hex { return /^0x[0-9a-f-f]*$/i.test(value); }
function normalizeKey(value:string): `0x${string}` { const raw=value.startsWith("0x")?value.slice(2):value; if(!/^[0-9a-f]{64}$/i.test(raw)) throw new Error("Invalid Altana session master key"); return `0x${raw}`; }
function listAddresses(name:string): Address[] { return (process.env[name]||"").split(",").map(x=>x.trim()).filter(Boolean).map(x=>{if(!isAddress(x)) throw new Error(`${name} contains an invalid address`);return x as Address;}); }
function listSelectors(): Hex[] { return (process.env.ALTANA_ALLOWED_SELECTORS||"").split(",").map(x=>x.trim()).filter(Boolean).map(x=>{if(!isHex(x)||x.length!==10) throw new Error("ALTANA_ALLOWED_SELECTORS contains an invalid selector");return x as Hex;}); }
function sessionDescriptor(jobId:number,walletAddress:string){
 if(!Number.isSafeInteger(jobId)||jobId<=0) throw new Error("jobId must be a positive integer"); if(!isAddress(walletAddress)) throw new Error("walletAddress is invalid");
 const master=normalizeKey(process.env.ALTANA_SESSION_PRIVATE_KEY||""); const sessionKey=`0x${createHmac("sha256",master.slice(2)).update(`${process.env.EXECUTION_AGENT_KIND||"agent"}-job-session:${jobId}`).digest("hex")}` as `0x${string}`;
 const expiry=Number(process.env.ALTANA_SESSION_EXPIRY||0); const spendToken=(process.env.ALTANA_SESSION_SPEND_TOKEN||"") as Address; const spendLimit=BigInt(process.env.ALTANA_SESSION_SPEND_LIMIT||"0"); const nativeSpendLimit=BigInt(process.env.ALTANA_SESSION_NATIVE_SPEND_LIMIT||"0");
 const targets=listAddresses("ALTANA_ALLOWED_TARGETS"); const selectors=listSelectors(); if(expiry<=Math.floor(Date.now()/1000)) throw new Error("ALTANA_SESSION_EXPIRY is missing or expired"); if(!isAddress(spendToken)) throw new Error("ALTANA_SESSION_SPEND_TOKEN is required"); if(spendLimit<=0n||nativeSpendLimit<=0n) throw new Error("Altana spend limits must be positive"); if(!targets.length||!selectors.length) throw new Error("Altana target and selector allowlists are required");
 return {walletAddress:walletAddress as Address,sessionPrivateKey:sessionKey,sessionAddress:(awaitImportAccount(sessionKey)),sessionPublicKey:"",expiry,spendToken,spendLimit,nativeSpendLimit,targets,selectors};
}
async function awaitImportAccount(key:`0x${string}`){ const {privateKeyToAccount}=await import("viem/accounts"); return privateKeyToAccount(key).address; }

async function executeCalls(jobId:number,walletAddress:string,calls:Array<{to:Address,data:Hex,value:bigint}>,spendToken:Address,spendAmount:bigint){
 const d=sessionDescriptor(jobId,walletAddress); for(const c of calls){if(!d.targets.some(x=>x.toLowerCase()===c.to.toLowerCase())) throw new Error(`Execution target ${c.to} is not allowlisted`); const selector=c.data.slice(0,10).toLowerCase(); if(!d.selectors.some(x=>x.toLowerCase()===selector)) throw new Error(`Execution selector ${selector} is not allowlisted`); if(c.value<0n) throw new Error("negative value");}
 if(spendAmount>d.spendLimit) throw new Error("Spend cap exceeded");
 const account=await import("viem/accounts").then(x=>x.privateKeyToAccount(d.sessionPrivateKey));
 const client=createClient({chains:[BNB_TESTNET]}); const session={walletAddress:d.walletAddress,signer:signerFromPrivateKey(d.sessionPrivateKey),publicKey:account.publicKey,permissions:{calls:calls.map(c=>({to:c.to})),spend:[{limit:d.spendLimit,period:"day" as const,token:d.spendToken},{limit:d.nativeSpendLimit,period:"day" as const}]},expiry:d.expiry};
 const result=await client.execute({session,calls,chainId:CHAIN_ID}); if(result.status==="FAILED") throw new Error(`Altana execution failed for ${result.callsId}`); return {status:result.status,transactionHash:result.transactionHash??null,callsId:result.callsId,network:NETWORK,chain_id:CHAIN_ID};
}
function json(res:any,status:number,body:any){const raw=JSON.stringify(body);res.writeHead(status,{"content-type":"application/json"});res.end(raw);}
async function readBody(req:any){const chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));const body=JSON.parse(Buffer.concat(chunks).toString("utf8"));if(!body||typeof body!=="object")throw new Error("Request body must be an object");return body;}

const server=createServer(async(req,res)=>{try{
 const url=new URL(req.url||"/","http://127.0.0.1");
 if(req.method==="GET"&&url.pathname==="/health")return json(res,200,{status:"ok",network:NETWORK,chain_id:CHAIN_ID,agent:process.env.EXECUTION_AGENT_KIND||"agent"});
 if(req.method==="GET"&&url.pathname==="/execution-capabilities") return json(res,200,{type:"agent-execution-capability-v1",agent:process.env.EXECUTION_AGENT_KIND||"agent",network:NETWORK,chain_id:CHAIN_ID,wallet_provider:"altana",authorization_model:"scoped_session",allowed_targets:listAddresses("ALTANA_ALLOWED_TARGETS"),allowed_selectors:listSelectors(),protocols:["pancake-v3-swap","pancake-v3-lp-range-management"],session_scope:"request-scoped",private_key_exposed:false,position_manager:process.env.PANCAKE_V3_POSITION_MANAGER||null});
 if(req.method==="POST"&&url.pathname==="/execute-swap"){const b=await readBody(req);const router=String(process.env.ALTANA_SWAP_ROUTER||"") as Address;const wallet=String(b.walletAddress||"");const tokenIn=String(b.tokenIn||"") as Address;const tokenOut=String(b.tokenOut||"") as Address;const fee=Number(b.fee??process.env.ALTANA_SWAP_FEE??2500);const amountIn=BigInt(String(b.amountIn||"0"));const min=BigInt(String(b.amountOutMinimum||"0"));if(!isAddress(router)||!isAddress(wallet)||!isAddress(tokenIn)||!isAddress(tokenOut)||amountIn<=0n)throw new Error("Invalid swap parameters");const data=encodeFunctionData({abi:SWAP_ABI,functionName:"exactInputSingle",args:[{tokenIn,tokenOut,fee,recipient:wallet,amountIn,amountOutMinimum:min,sqrtPriceLimitX96:0n}]});const allowance=await publicClient.readContract({address:tokenIn,abi:ERC20_ABI,functionName:"allowance",args:[wallet,router]});if(allowance<amountIn)throw new Error("ERC-20 allowance is insufficient for the swap");return json(res,200,await executeCalls(Number(b.jobId),wallet,[{to:router,data,value:0n}],tokenIn,amountIn));}
 if(req.method==="POST"&&url.pathname==="/execute-lp-withdraw"){const b=await readBody(req);const pm=String(b.positionManager||process.env.PANCAKE_V3_POSITION_MANAGER||"") as Address;const wallet=String(b.walletAddress||"");const tokenId=BigInt(String(b.tokenId||"0"));const liquidity=BigInt(String(b.liquidity||"0"));const deadline=BigInt(Math.floor(Date.now()/1000)+600);if(!isAddress(pm)||!isAddress(wallet)||tokenId<=0n||liquidity<=0n)throw new Error("Invalid LP withdrawal parameters");const decrease=encodeFunctionData({abi:LP_ABI,functionName:"decreaseLiquidity",args:[{tokenId,liquidity,amount0Min:0n,amount1Min:0n,deadline}]});const collect=encodeFunctionData({abi:LP_ABI,functionName:"collect",args:[{tokenId,recipient:wallet,amount0Max:2n**128n-1n,amount1Max:2n**128n-1n}]});const burn=encodeFunctionData({abi:LP_ABI,functionName:"burn",args:[tokenId]});return json(res,200,await executeCalls(Number(b.jobId),wallet,[{to:pm,data:decrease,value:0n},{to:pm,data:collect,value:0n},{to:pm,data:burn,value:0n}],process.env.ALTANA_SESSION_SPEND_TOKEN as Address,0n));}
 if(req.method==="POST"&&url.pathname==="/execute-lp-mint"){const b=await readBody(req);const pm=String(b.positionManager||process.env.PANCAKE_V3_POSITION_MANAGER||"") as Address;const wallet=String(b.walletAddress||"");const token0=String(b.token0||"") as Address;const token1=String(b.token1||"") as Address;const a0=BigInt(String(b.amount0Desired||"0"));const a1=BigInt(String(b.amount1Desired||"0"));if(!isAddress(pm)||!isAddress(wallet)||!isAddress(token0)||!isAddress(token1)||a0<0n||a1<0n||a0+a1<=0n)throw new Error("Invalid LP mint parameters");const al0=await publicClient.readContract({address:token0,abi:ERC20_ABI,functionName:"allowance",args:[wallet,pm]});const al1=await publicClient.readContract({address:token1,abi:ERC20_ABI,functionName:"allowance",args:[wallet,pm]});if(al0<a0||al1<a1)throw new Error("LP position manager allowance is insufficient; approve both tokens before execution");const deadline=BigInt(Math.floor(Date.now()/1000)+600);const data=encodeFunctionData({abi:LP_ABI,functionName:"mint",args:[{token0,token1,fee:Number(b.fee),tickLower:Number(b.tickLower),tickUpper:Number(b.tickUpper),amount0Desired:a0,amount1Desired:a1,amount0Min:0n,amount1Min:0n,recipient:wallet,deadline}]});return json(res,200,await executeCalls(Number(b.jobId),wallet,[{to:pm,data,value:0n}],process.env.ALTANA_SESSION_SPEND_TOKEN as Address,0n));}
 if(req.method==="POST"&&url.pathname==="/preflight") return json(res,200,{broadcast:false,network:NETWORK,chain_id:CHAIN_ID,capabilities:"/execution-capabilities"});
 return json(res,404,{error:"not_found"});
}catch(error){json(res,400,{error:error instanceof Error?error.message:String(error)});}});
server.listen(PORT,"127.0.0.1",()=>console.log(`new-agent execution runtime listening on ${PORT}`));
