import { createHmac } from "node:crypto";
import { createServer } from "node:http";
import { BNB_TESTNET, createClient, signerFromPrivateKey } from "@altananetwork/sdk";
import { createPublicClient, encodeFunctionData, http, type Address, type Hex } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { bscTestnet } from "viem/chains";

const PORT = Number(process.env.EXECUTION_PORT || 8788);
const NETWORK = "bsc-testnet" as const;
const CHAIN_ID = 97;
const publicClient = createPublicClient({ chain: bscTestnet, transport: http(process.env.BSC_TESTNET_RPC_URL || "https://bsc-testnet-rpc.publicnode.com") });
const SWAP_ABI = [{type:"function",name:"exactInputSingle",stateMutability:"payable",inputs:[{name:"params",type:"tuple",components:[{name:"tokenIn",type:"address"},{name:"tokenOut",type:"address"},{name:"fee",type:"uint24"},{name:"recipient",type:"address"},{name:"amountIn",type:"uint256"},{name:"amountOutMinimum",type:"uint256"},{name:"sqrtPriceLimitX96",type:"uint160"}]}],outputs:[{name:"amountOut",type:"uint256"}]}] as const;
const LP_ABI = [
 {type:"function",name:"decreaseLiquidity",stateMutability:"nonpayable",inputs:[{name:"params",type:"tuple",components:[{name:"tokenId",type:"uint256"},{name:"liquidity",type:"uint128"},{name:"amount0Min",type:"uint256"},{name:"amount1Min",type:"uint256"},{name:"deadline",type:"uint256"}]}],outputs:[{name:"amount0",type:"uint256"},{name:"amount1",type:"uint256"}]},
 {type:"function",name:"collect",stateMutability:"payable",inputs:[{name:"params",type:"tuple",components:[{name:"tokenId",type:"uint256"},{name:"recipient",type:"address"},{name:"amount0Max",type:"uint128"},{name:"amount1Max",type:"uint128"}]}],outputs:[{name:"amount0",type:"uint256"},{name:"amount1",type:"uint256"}]},
 {type:"function",name:"burn",stateMutability:"nonpayable",inputs:[{name:"tokenId",type:"uint256"}],outputs:[]},
 {type:"function",name:"mint",stateMutability:"payable",inputs:[{name:"params",type:"tuple",components:[{name:"token0",type:"address"},{name:"token1",type:"address"},{name:"fee",type:"uint24"},{name:"tickLower",type:"int24"},{name:"tickUpper",type:"int24"},{name:"amount0Desired",type:"uint256"},{name:"amount1Desired",type:"uint256"},{name:"amount0Min",type:"uint256"},{name:"amount1Min",type:"uint256"},{name:"recipient",type:"address"},{name:"deadline",type:"uint256"}]}],outputs:[{name:"tokenId",type:"uint256"},{name:"liquidity",type:"uint128"},{name:"amount0",type:"uint256"},{name:"amount1",type:"uint256"}]}
] as const;
const ERC20_ABI = [{type:"function",name:"allowance",stateMutability:"view",inputs:[{name:"owner",type:"address"},{name:"spender",type:"address"}],outputs:[{name:"remaining",type:"uint256"}]}] as const;
function isAddress(v:string):v is Address{return /^0x[0-9a-f]{40}$/i.test(v)}
function isHex(v:string):v is Hex{return /^0x[0-9a-f]*$/i.test(v)}
function normalizeKey(v:string):`0x${string}`{const r=v.startsWith("0x")?v.slice(2):v;if(!/^[0-9a-f]{64}$/i.test(r))throw new Error("Invalid Altana session master key");return `0x${r}`}
function addresses(name:string):Address[]{return(process.env[name]||"").split(",").map(x=>x.trim()).filter(Boolean).map(x=>{if(!isAddress(x))throw new Error(`${name} contains invalid address`);return x as Address})}
function selectors():Hex[]{return(process.env.ALTANA_ALLOWED_SELECTORS||"").split(",").map(x=>x.trim()).filter(Boolean).map(x=>{if(!isHex(x)||x.length!==10)throw new Error("ALTANA_ALLOWED_SELECTORS contains invalid selector");return x as Hex})}
function descriptor(jobId:number,walletAddress:string){if(!Number.isSafeInteger(jobId)||jobId<=0)throw new Error("jobId must be a positive integer");if(!isAddress(walletAddress))throw new Error("walletAddress is invalid");const master=normalizeKey(process.env.ALTANA_SESSION_PRIVATE_KEY||"");const sessionPrivateKey=`0x${createHmac("sha256",master.slice(2)).update(`${process.env.EXECUTION_AGENT_KIND||"agent"}-job-session:${jobId}`).digest("hex")}` as `0x${string}`;const account=privateKeyToAccount(sessionPrivateKey);const expiry=Number(process.env.ALTANA_SESSION_EXPIRY||0);const spendToken=process.env.ALTANA_SESSION_SPEND_TOKEN as Address;const spendLimit=BigInt(process.env.ALTANA_SESSION_SPEND_LIMIT||"0");const nativeSpendLimit=BigInt(process.env.ALTANA_SESSION_NATIVE_SPEND_LIMIT||"0");const targets=addresses("ALTANA_ALLOWED_TARGETS");const allowedSelectors=selectors();if(expiry<=Math.floor(Date.now()/1000))throw new Error("ALTANA_SESSION_EXPIRY is missing or expired");if(!isAddress(String(spendToken||"")))throw new Error("ALTANA_SESSION_SPEND_TOKEN is required");if(spendLimit<=0n||nativeSpendLimit<=0n)throw new Error("Altana spend limits must be positive");if(!targets.length||!allowedSelectors.length)throw new Error("Altana target and selector allowlists are required");return{walletAddress:walletAddress as Address,sessionPrivateKey,account,expiry,spendToken,spendLimit,nativeSpendLimit,targets,allowedSelectors}}
async function executeCalls(jobId:number,walletAddress:string,calls:Array<{to:Address,data:Hex,value:bigint}>,extraSpendTokens:Address[]=[]){const d=descriptor(jobId,walletAddress);for(const c of calls){if(!d.targets.some(x=>x.toLowerCase()===c.to.toLowerCase()))throw new Error(`Execution target ${c.to} is not allowlisted`);const selector=c.data.slice(0,10).toLowerCase();if(!d.allowedSelectors.some(x=>x.toLowerCase()===selector))throw new Error(`Execution selector ${selector} is not allowlisted`);if(c.value<0n)throw new Error("negative value")};const spend=[{limit:d.spendLimit,period:"day" as const,token:d.spendToken},...extraSpendTokens.filter(x=>x.toLowerCase()!==d.spendToken.toLowerCase()).map(token=>({limit:d.spendLimit,period:"day" as const,token}))];const client=createClient({chains:[BNB_TESTNET]});const session={walletAddress:d.walletAddress,signer:signerFromPrivateKey(d.sessionPrivateKey),publicKey:d.account.publicKey,permissions:{calls:calls.map(c=>({to:c.to})),spend:[...spend,{limit:d.nativeSpendLimit,period:"day" as const}]},expiry:d.expiry};const result=await client.execute({session,calls,chainId:CHAIN_ID});if(result.status==="FAILED")throw new Error(`Altana execution failed for ${result.callsId}`);return{status:result.status,transactionHash:result.transactionHash??null,callsId:result.callsId,network:NETWORK,chain_id:CHAIN_ID}}
function send(res:any,status:number,body:any){res.writeHead(status,{"content-type":"application/json"});res.end(JSON.stringify(body))}
async function body(req:any){const chunks:Buffer[]=[];for await(const c of req)chunks.push(Buffer.from(c));const b=JSON.parse(Buffer.concat(chunks).toString("utf8"));if(!b||typeof b!=="object")throw new Error("Request body must be an object");return b}
const server=createServer(async(req,res)=>{try{const url=new URL(req.url||"/","http://127.0.0.1");if(req.method==="GET"&&url.pathname==="/health")return send(res,200,{status:"ok",network:NETWORK,chain_id:CHAIN_ID,agent:process.env.EXECUTION_AGENT_KIND||"agent"});if(req.method==="GET"&&url.pathname==="/execution-capabilities")return send(res,200,{type:"agent-execution-capability-v1",agent:process.env.EXECUTION_AGENT_KIND||"agent",network:NETWORK,chain_id:CHAIN_ID,wallet_provider:"altana",authorization_model:"scoped_session",allowed_targets:addresses("ALTANA_ALLOWED_TARGETS"),allowed_selectors:selectors(),protocols:["pancake-v3-swap","pancake-v3-lp-range-management"],session_scope:"request-scoped",private_key_exposed:false,position_manager:process.env.PANCAKE_V3_POSITION_MANAGER||null});if(req.method==="POST"&&url.pathname==="/execute-swap"){const b=await body(req);const router=String(process.env.ALTANA_SWAP_ROUTER||"") as Address;const wallet=String(b.walletAddress||"");const tokenIn=String(b.tokenIn||"") as Address;const tokenOut=String(b.tokenOut||"") as Address;const amountIn=BigInt(String(b.amountIn||"0"));const fee=Number(b.fee??2500);const min=BigInt(String(b.amountOutMinimum||"0"));if(!isAddress(router)||!isAddress(wallet)||!isAddress(tokenIn)||!isAddress(tokenOut)||amountIn<=0n)throw new Error("Invalid swap parameters");const allowance=await publicClient.readContract({address:tokenIn,abi:ERC20_ABI,functionName:"allowance",args:[wallet,router]});if(allowance<amountIn)throw new Error("ERC-20 allowance is insufficient for the swap");const data=encodeFunctionData({abi:SWAP_ABI,functionName:"exactInputSingle",args:[{tokenIn,tokenOut,fee,recipient:wallet,amountIn,amountOutMinimum:min,sqrtPriceLimitX96:0n}]});return send(res,200,await executeCalls(Number(b.jobId),wallet,[{to:router,data,value:0n}]));}
if(req.method==="POST"&&url.pathname==="/execute-lp-withdraw"){const b=await body(req);const pm=String(b.positionManager||process.env.PANCAKE_V3_POSITION_MANAGER||"") as Address;const wallet=String(b.walletAddress||"");const tokenId=BigInt(String(b.tokenId||"0"));const liquidity=BigInt(String(b.liquidity||"0"));if(!isAddress(pm)||!isAddress(wallet)||tokenId<=0n||liquidity<=0n)throw new Error("Invalid LP withdrawal parameters");const deadline=BigInt(Math.floor(Date.now()/1000)+600);const decrease=encodeFunctionData({abi:LP_ABI,functionName:"decreaseLiquidity",args:[{tokenId,liquidity,amount0Min:0n,amount1Min:0n,deadline}]});const collect=encodeFunctionData({abi:LP_ABI,functionName:"collect",args:[{tokenId,recipient:wallet,amount0Max:2n**128n-1n,amount1Max:2n**128n-1n}]});const burn=encodeFunctionData({abi:LP_ABI,functionName:"burn",args:[tokenId]});return send(res,200,await executeCalls(Number(b.jobId),wallet,[{to:pm,data:decrease,value:0n},{to:pm,data:collect,value:0n},{to:pm,data:burn,value:0n}]));}
if(req.method==="POST"&&url.pathname==="/execute-lp-mint"){const b=await body(req);const pm=String(b.positionManager||process.env.PANCAKE_V3_POSITION_MANAGER||"") as Address;const wallet=String(b.walletAddress||"");const token0=String(b.token0||"") as Address;const token1=String(b.token1||"") as Address;const a0=BigInt(String(b.amount0Desired||"0"));const a1=BigInt(String(b.amount1Desired||"0"));if(!isAddress(pm)||!isAddress(wallet)||!isAddress(token0)||!isAddress(token1)||a0<0n||a1<0n||a0+a1<=0n)throw new Error("Invalid LP mint parameters");const al0=await publicClient.readContract({address:token0,abi:ERC20_ABI,functionName:"allowance",args:[wallet,pm]});const al1=await publicClient.readContract({address:token1,abi:ERC20_ABI,functionName:"allowance",args:[wallet,pm]});if(al0<a0||al1<a1)throw new Error("LP position manager allowance is insufficient; approve both tokens before execution");const deadline=BigInt(Math.floor(Date.now()/1000)+600);const data=encodeFunctionData({abi:LP_ABI,functionName:"mint",args:[{token0,token1,fee:Number(b.fee),tickLower:Number(b.tickLower),tickUpper:Number(b.tickUpper),amount0Desired:a0,amount1Desired:a1,amount0Min:0n,amount1Min:0n,recipient:wallet,deadline}]});return send(res,200,await executeCalls(Number(b.jobId),wallet,[{to:pm,data,value:0n}],[token0,token1]));}
if(req.method==="POST"&&url.pathname==="/preflight")return send(res,200,{broadcast:false,network:NETWORK,chain_id:CHAIN_ID,allowed_targets:addresses("ALTANA_ALLOWED_TARGETS"),allowed_selectors:selectors()});return send(res,404,{error:"not_found"});}catch(e){send(res,400,{error:e instanceof Error?e.message:String(e)})}});
server.listen(PORT,"127.0.0.1",()=>console.log(`new-agent execution runtime listening on ${PORT}`));