import { useEffect, useMemo, useState } from "react";
import { parseMarketplaceIntent } from "./lib/intent";

type Agent={id?:string;agent_id:string;name:string|null;description:string|null;category:string;status?:string|null;verification_status?:string|null};
type Match={agent:Agent;score:number;breakdown:Record<string,number>;reasons?:string[];hireability?:{status:"ready"|"degraded"|"discoverable_only";canCreateJob:boolean;reason:string}};
type MatchResponse={intent:ReturnType<typeof parseMarketplaceIntent>;bestMatch:Match|null;bestHireableMatch?:Match|null;alternatives:Match[]};
type CapInput={name:string;label:string;type:string;required?:boolean;help?:string}; type Cap={version?:number;inputs?:CapInput[];defaults?:Record<string,unknown>}; type CapResponse={capability:Cap;agent:{owner:string;category:string}};
type MissionResponse={mission:{id:string;title?:string;category?:string};task:{id:string};job:{id:string;status:string}};
type QuoteResponse={ok:boolean;quote:{quote_id:string;price:string;currency:string;quote_hash:string|null;status:string;expires_at:string};provider?:{agent_id:string;name:string|null;endpoint:string;status:string|null;wallet_address?:string};signature_present?:boolean};
type Prepared=Record<string,any>;
const examples=["Manage my BNB portfolio conservatively","Find a safe yield strategy for my idle assets","Monitor my lending health factor and liquidation risk","Run a controlled grid strategy"];
const human=(v:string)=>v.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase()); const compact=(v?:string|null)=>v?`${v.slice(0,6)}…${v.slice(-4)}`:"—";
const read=async(r:Response)=>{const raw=await r.text();let b:any=null;try{b=raw?JSON.parse(raw):null}catch{throw Error(`${r.status}: ${raw.slice(0,180)}`)}if(!r.ok)throw Error(b?.error||"Request failed");return b};
function Info({title,value,mono=false,green=false}:{title:string;value:string;mono?:boolean;green?:boolean}){return <div className="border border-line rounded-[12px_7px_13px_8px] bg-paper p-3"><small className="block font-mono text-[8px] uppercase text-[#8a8477] mb-1">{title}</small><strong className={`${mono?"font-mono text-[11px]":"font-display text-[14px]"} ${green?"text-green":""}`}>{value}</strong></div>}
export default function MarketplaceWorkspace(){
 const[goal,setGoal]=useState(examples[0]),[result,setResult]=useState<MatchResponse|null>(null),[selected,setSelected]=useState<Match|null>(null),[cap,setCap]=useState<CapResponse|null>(null),[params,setParams]=useState<Record<string,any>>({}),[yieldText,setYieldText]=useState(""),[mission,setMission]=useState<MissionResponse|null>(null),[quote,setQuote]=useState<QuoteResponse|null>(null),[prepared,setPrepared]=useState<Prepared|null>(null),[step,setStep]=useState(1),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[ttl,setTtl]=useState(0);
 const intent=useMemo(()=>parseMarketplaceIntent(goal),[goal]); const best=selected||result?.bestHireableMatch||result?.bestMatch;
 useEffect(()=>{if(!quote?.quote.expires_at)return;const f=()=>setTtl(Math.max(0,Math.floor((new Date(quote.quote.expires_at).getTime()-Date.now())/1000)));f();const i=setInterval(f,1000);return()=>clearInterval(i)},[quote?.quote.expires_at]); useEffect(()=>{if(new URLSearchParams(location.search).get("funded")==="1")setStep(6)},[]);
 async function findAgent(){setLoading(true);setError("");try{const r=await read(await fetch("/api/testnet/match",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal})})) as MatchResponse;const b=r.bestHireableMatch||r.bestMatch;if(!b)throw Error("No suitable Testnet agent found.");const c=await read(await fetch(`/api/testnet/capabilities?agent_id=${encodeURIComponent(b.agent.agent_id)}`)) as CapResponse;setResult(r);setSelected(b);setCap(c);setParams({});setYieldText("");setStep(2)}catch(e){setError(e instanceof Error?e.message:"Unable to resolve agent capability")}finally{setLoading(false)}}
 function structured(){if(!best)return{};if(best.agent.category==="grid_trading")return{category:"grid_trading",lower_price:600,upper_price:700,grid_levels:12,notional:100,max_slippage_bps:50};if(best.agent.category==="rebalancing")return{current_tick:Number(params.current_tick),tick_lower:Number(params.tick_lower),tick_upper:Number(params.tick_upper)};if(best.agent.category==="health_factor")return{health_factor:Number(params.health_factor)};if(best.agent.category==="yield")return{opportunities:yieldText.split(/\n+/).map(x=>x.trim()).filter(Boolean).map(x=>{const[a="",b="",c="",d=""]=x.split("|").map(y=>y.trim());return{protocol:a,market:b,apr:Number(c),target:d}}).filter(x=>Number.isFinite(x.apr))};return{...params}}
 function validate(p:Record<string,any>){if(!best||best.agent.category==="grid_trading")return;for(const i of(cap?.capability.inputs||[])){if(i.required!==false&&(p[i.name]===undefined||p[i.name]===null||p[i.name]===""||(Array.isArray(p[i.name])&&!p[i.name].length)))throw Error(`${i.name} is required.`)}if(best.agent.category==="rebalancing"&&p.tick_upper<=p.tick_lower)throw Error("Upper tick must be greater than lower tick.");if(best.agent.category==="health_factor"&&p.health_factor<=0)throw Error("Health factor must be positive.")}
 async function hire(){if(!best)return;if(!best.hireability?.canCreateJob){setError(best.hireability?.reason||"Provider not ready.");return}setBusy(true);setError("");try{const auth=await read(await fetch("/api/auth/me",{credentials:"include"}));if(!auth?.user)throw Error("Connect and sign in with your Testnet wallet first.");const p=structured();validate(p);const m=await read(await fetch("/api/missions",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal,agent_id:best.agent.agent_id,budget:0})})) as MissionResponse;setMission(m);if(!best.agent.id)throw Error("Selected provider is missing its database id.");const q=await read(await fetch("/api/testnet/quotes",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({goal,agent_id:best.agent.id,parameters:p,mission_id:m.mission.id})})) as QuoteResponse;setQuote(q);setStep(3)}catch(e){setError(e instanceof Error?e.message:"Mission creation failed")}finally{setBusy(false)}}
 async function accept(){if(!quote)return;setBusy(true);try{setQuote(await read(await fetch("/api/testnet/quotes",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"accept",quote_id:quote.quote.quote_id})})));setStep(4)}catch(e){setError(e instanceof Error?e.message:"Quote acceptance failed")}finally{setBusy(false)}}
 async function prepare(){if(!quote||!mission)return;setBusy(true);try{const a=await read(await fetch("/api/auth/me",{credentials:"include"}));if(!a?.user?.wallet_address)throw Error("Connect and sign in with your Testnet wallet first.");setPrepared(await read(await fetch("/api/testnet/prepare-quote",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({mission_id:mission.mission.id,quote_id:quote.quote.quote_id,client_address:a.user.wallet_address})})));setStep(5)}catch(e){setError(e instanceof Error?e.message:"Preparation failed")}finally{setBusy(false)}}
 const labels=["Goal","Match","Quote","Mission","Sign","Fund"],mins=Math.floor(ttl/60),secs=String(ttl%60).padStart(2,"0"),inputs=cap?.capability.inputs||[];
 return <main className="max-w-[1240px] mx-auto px-6 md:px-8 py-8 font-body text-ink"><section className="flex justify-between mb-5"><span className="font-mono text-[9px] uppercase text-[#8a8477]">Create mission / Hiring flow</span><button className="text-[11px] font-bold" onClick={()=>location.assign("/dashboard")}>✕ Close</button></section>{error&&<div className="mb-4 border border-[#cfad9f] bg-rustsoft text-rust rounded-[14px_8px_15px_9px] px-4 py-3 text-[12px]">{error}</div>}<div className="flex mb-8 overflow-x-auto">{labels.map((l,i)=><div key={l} className="flex-1 min-w-[70px] text-center"><b className={`mx-auto w-7 h-7 rounded-full flex items-center justify-center font-mono text-[10px] ${i+1<=step?"bg-ink text-paperhi":"bg-linesoft text-inksoft"}`}>{i+1}</b><span className="block font-mono text-[8px] uppercase mt-1">{l}</span></div>)}</div><div className="bg-paperhi border border-line card-asym-lg p-6 md:p-8 min-h-[420px]">
 {step===1&&<><h2 className="font-display text-[24px] font-bold mb-2">State the outcome you want.</h2><p className="text-[13px] text-inksoft mb-5">The marketplace matches the goal first, then loads that agent's required task inputs.</p><textarea value={goal} onChange={e=>setGoal(e.target.value)} rows={2} className="w-full border border-line rounded-[14px] bg-paper p-4 font-display text-[17px] outline-none mb-5"/><div className="grid sm:grid-cols-3 gap-3 mb-5"><Info title="Category" value={human(intent.category)}/><Info title="Risk" value={intent.risk}/><Info title="Keywords" value={goal.toLowerCase().split(/\s+/).filter(x=>x.length>3).slice(0,5).join(" · ")||"—"} mono/></div><button disabled={loading} onClick={()=>void findAgent()} className="font-display font-bold text-[12px] px-5 py-3 bg-ink text-paperhi btn-asym">{loading?"Matching…":"Find matching agents →"}</button></>}
 {step===2&&best&&<><h2 className="font-display text-[24px] font-bold mb-1">Confirm the inputs this agent requires.</h2><p className="text-[13px] text-inksoft mb-5">Only required fields from the selected agent capability schema are requested. Grid remains unchanged.</p><div className="border border-brass/40 bg-brasssoft/60 rounded-[16px] p-5 mb-4"><strong className="font-display text-[18px]">{best.agent.name||best.agent.agent_id}</strong><div className="text-[11px] text-inksoft mt-1">Provider wallet: {compact(cap?.agent.owner)}</div></div>{best.agent.category==="grid_trading"?<Info title="Grid task" value="Existing defaults unchanged: 600–700 · 12 levels · 100 notional · 50 bps slippage."/>:<div className="border border-line rounded-[14px] bg-paper p-4 mb-5"><div className="grid sm:grid-cols-2 gap-4">{inputs.map(i=>i.type==="opportunities"?<div key={i.name} className="sm:col-span-2"><label className="font-mono text-[9px] uppercase block mb-1">{i.label} · required</label><textarea rows={4} value={yieldText} onChange={e=>setYieldText(e.target.value)} placeholder="Protocol | market | APR | target" className="w-full border border-line rounded-[10px] bg-paperhi p-3 text-[12px]"/><small className="text-[10px] text-inksoft">{i.help}</small></div>:<div key={i.name}><label className="font-mono text-[9px] uppercase block mb-1">{i.label} · required</label><input type="number" value={params[i.name]??""} onChange={e=>setParams(v=>({...v,[i.name]:e.target.value}))} className="w-full border border-line rounded-[10px] bg-paperhi p-3 text-[12px]"/></div>)}</div></div>}<div className="flex gap-3"><button disabled={busy} onClick={()=>void hire()} className="font-display font-bold text-[12px] px-5 py-3 bg-ink text-paperhi btn-asym">{busy?"Getting quote…":"Confirm & get quote →"}</button><button onClick={()=>setStep(1)} className="font-bold text-[12px] px-4 py-3 text-inksoft">← Back</button></div></>}
 {step===3&&quote&&<><h2 className="font-display text-[24px] font-bold mb-2">The selected agent sets the price.</h2><div className="grid sm:grid-cols-2 gap-3 mb-6"><Info title="Quoted price" value={`${quote.quote.price} ${quote.quote.currency}`} mono/><Info title="Provider wallet" value={compact(quote.provider?.wallet_address)} mono/><Info title="Quote hash" value={compact(quote.quote.quote_hash)} mono/><Info title="Expires" value={ttl>0?`in ${mins}:${secs}`:"expired"}/></div><div className="flex gap-3"><button disabled={busy||ttl<=0} onClick={()=>void accept()} className="font-display font-bold text-[12px] px-5 py-3 bg-ink text-paperhi btn-asym">{busy?"Accepting…":"Accept quote →"}</button><button onClick={()=>setStep(2)} className="font-bold text-[12px] px-4 py-3 text-inksoft">← Back</button></div></>}
 {step===4&&mission&&quote&&<><h2 className="font-display text-[24px] font-bold mb-2">Mission created.</h2><div className="grid sm:grid-cols-2 gap-3 mb-6"><Info title="Assigned agent" value={selected?.agent.name||"Provider"}/><Info title="Category" value={human(mission.mission.category||intent.category)}/><Info title="Accepted quote" value={`${quote.quote.price} ${quote.quote.currency}`} mono/><Info title="Mission status" value="Open — not yet funded"/></div><button disabled={busy} onClick={()=>void prepare()} className="font-display font-bold text-[12px] px-5 py-3 bg-ink text-paperhi btn-asym">{busy?"Preparing…":"Prepare ERC-8183 job →"}</button></>}
 {step===5&&prepared&&<><h2 className="font-display text-[24px] font-bold mb-2">Your wallet signs the job steps.</h2><p className="text-[13px] text-inksoft mb-5">The backend has prepared the real transaction payloads. Wallet execution remains client-side and non-custodial.</p><div className="border border-line rounded-[16px] overflow-hidden mb-6"><div className="p-4 border-b dash-b bg-paper"><div className="grid sm:grid-cols-2 gap-3"><Info title="Token" value={String(prepared.payment?.symbol||"—")} mono/><Info title="Balance" value={String(prepared.payment?.balance_formatted||"—")} mono/></div></div><div className="p-5 bg-paper"><div className="text-[12px] text-inksoft mb-2">Prepared quote: <span className="font-mono">{String(prepared.quote?.price||"—")} {String(prepared.quote?.currency||"")}</span></div><div className="text-[11px] text-inksoft">{String(prepared.job_description||"")}</div></div></div><div className="flex gap-3"><button onClick={()=>location.assign(`/testnet/execute?mission=${encodeURIComponent(mission?.mission.id||"")}`)} className="font-display font-bold text-[12px] px-5 py-3 bg-ink text-paperhi btn-asym">Open wallet execution →</button><button onClick={()=>setStep(4)} className="font-bold text-[12px] px-4 py-3 text-inksoft">← Back</button></div></>}
 {step===6&&<><h2 className="font-display text-[24px] font-bold mb-2">Funded, on-chain.</h2><p className="text-[13px] text-inksoft mb-5">The wallet execution route has returned to the hiring flow. Continue from the real job record rather than assuming a transaction succeeded.</p><div className="grid sm:grid-cols-2 gap-3 mb-6"><Info title="Status" value="Funded" green/><Info title="Network" value="BSC Testnet · Chain 97"/><Info title="Mission" value={mission?.mission.title||"Testnet mission"}/><Info title="Job" value={compact(mission?.job.id)} mono/></div><div className="flex gap-3"><button onClick={()=>location.assign(`/dashboard?tab=missions`)} className="font-display font-bold text-[12px] px-5 py-3 bg-ink text-paperhi btn-asym">Go to Missions →</button><button onClick={()=>location.assign(`/dashboard?job=${encodeURIComponent(mission?.job.id||"")}`)} className="font-bold text-[12px] px-4 py-3 text-inksoft">Open mission console</button></div></>}
 </div></main>;
}
